[features]
seeds = false
[programs.localnet]
dex_program = "AzGjndwsJTbc1XRzPkmuFk11V88dNLMiQwGqkqkS1vBD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --detectOpenHandles --forceExit"
